//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeNTrack.Models
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;


    public partial class Activity
    {
        public int ActivityID { get; set; }
        public string ActTitle { get; set; }
        public DateTime ActDate { get; set; }
        public Nullable<System.TimeSpan> ActTime { get; set; }
        public string ActLocation { get; set; }
        public string ActDescription { get; set; }
        public string ActOOTD { get; set; }
        public Nullable<System.DateTime> ActCreated { get; set; }
        public string ActRemark { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
