//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeNTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public int AnnouncementID { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> AnnounceAt { get; set; }
        public Nullable<int> AdminID { get; set; }
    
        public virtual User User { get; set; }
    }
}
